<?php
/*
Plugin Name: bbPress SVN Tracker
Version: 1.0
*/

/************************************************************
 * Do not edit this file.  All configuration options should *
 * be changed in bb-svn-tracker-config.php.                 *
 ************************************************************/

if ( file_exists( dirname(__FILE__) . '/bb-svn-tracker-config.php' ) )
	require( dirname(__FILE__) . '/bb-svn-tracker-config.php' );
else
	require( dirname(dirname(__FILE__)) . '/bb-svn-tracker-config.php' );

require( dirname(__FILE__) . '/class.bbpress-plugins-tracker.php' );

if ( defined( 'BBPRESS_SVN_TRACKER__INCLUDE' ) && file_exists( BBPRESS_SVN_TRACKER__INCLUDE ) )
	include( BBPRESS_SVN_TRACKER__INCLUDE );


function bb_svn_tracker_topic_link( $url ) {
	return rtrim( $url, '/' ) . '/';
}

function bb_svn_tracker_view_link( $url, $view ) {
	return str_replace( "/view/$view", "/browse/$view", $url);
}

function bb_svn_tracker_show_only_public_tags( $topic_id ) {
	global $other_tags, $user_tags;
	$user_tags = false;
	if ( !$other_tags = bb_get_public_tags( $topic_id ) )
		$other_tags = false;
}

function bb_svn_tracker_activate_plugin() {
	global $svn_tracker;
	define( 'AUTOMATTIC_SVN_TRACKER__CREATE_TABLES', true );
	$svn_tracker->create_tables();
}

if ( bb_get_option( 'mod_rewrite' ) ) {
	add_filter( 'get_topic_link', 'bb_svn_tracker_topic_link' );
	//add_filter( 'get_view_link', 'bb_svn_tracker_view_link', 10, 2 );
}

add_action( 'bb_topic.php', 'bb_svn_tracker_show_only_public_tags' );
add_action( 'bb_activate_plugin_' . substr( __FILE__, strlen( BBPLUGINDIR ) ), 'bb_svn_tracker_activate_plugin' );

if ( !defined( 'BBPRESS_SVN_TRACKER__TRACKER_CLASS' ) )
	define( 'BBPRESS_SVN_TRACKER__TRACKER_CLASS', 'bbPress_Plugins_Tracker' );

if ( !defined( 'BBPRESS_SVN_TRACKER__ADMIN_CLASS' ) )
	define( 'BBPRESS_SVN_TRACKER__ADMIN_CLASS', false );
elseif ( !class_exists( 'bbPress_SVN_Admin' ) )
	require( dirname( __FILE__ ) . '/class.bbpress-svn-admin.php' );

$bb_svn_tracker_class = BBPRESS_SVN_TRACKER__TRACKER_CLASS;

$GLOBALS['svn_tracker'] = &new $bb_svn_tracker_class(
	$bbdb,
	BBPRESS_SVN_TRACKER__SVN_URL,
	BBPRESS_SVN_TRACKER__ADMIN_CLASS
);

unset($bb_svn_tracker_class);

add_action( 'bb_init', array(&$GLOBALS['svn_tracker'], 'init') );

?>
