<?php
/*
Plugin Name: Upgrade Else DIE!
Plugin URI: http://www.gaut.am/bbpress/plugins/upgrade-else-die/
Description: Upgrade Else DIE is not a plugin for those who are interested in offering users a choice between upgrading from IE6 or viewing the site in their current outdated browser. This plugin is mean and aggressive in that it will NOT allow anyone using IE6 to view your site until they upgrade! The Plugin is inspired from <a href="http://eight7teen.com/upgrade-else-die/">Upgrade Else Die</a> plugin for WordPress by Josh.
Version: 0.1
Author: Gautam Gupta
Author URI: http://gaut.am/
*/

/*
 Main PHP File for
 Upgrade Else Die Plugin (for bbPress) by www.gaut.am
*/

// define the needed locations
define('UPGRADEELSEDIE_IMGLOC', bb_get_option('uri').trim(str_replace(array(trim(BBPATH,"/\\"),"\\"),array("","/"),dirname(__FILE__)),' /\\').'/images/');
define('UPGRADEELSEDIE_PLUGPATH', bb_get_option('uri').trim(str_replace(array(trim(BBPATH,"/\\"),"\\"),array("","/"),dirname(__FILE__)),' /\\').'/');


//detect browser
$ie6 = "MSIE 6.0";
$browser = substr($_SERVER['HTTP_USER_AGENT'], 25, 8);

function upgrade_else_die_kill_ie6() {
    die(
    "
    <!-- Start of Code Generated by Upgrade Else Die Plugin By www.gaut.am -->
    <link rel='stylesheet' type='text/css' href='".UPGRADEELSEDIE_PLUGPATH."upgrade-else-die.css' />
    </head>
    <body>
    <div class='warn'>
    <h1>WARNING!</h1>
    <p>You are using Internet Explorer 6.0. Due to security risks associated
    with this outdated browser, as well as its noncompliance with WC3
    standards, I have disabled access for all Internet Explorer 6.0 users.</p>
    
    <p>I would love to share the content of this site with you, but unless
    you upgrade your browser, this is impossible. There are too many
    security risks posed by this outdated browser. Won't you please take
    a moment and upgrade - it's 100% free!</p>
    
    <p>If you are at your place of employment and do not have access or
    permission to upgrade your browser, please contact your company's IT
    department and request an upgraded browser, which will keep your
    company's information safe and secure. Upgrading will also improve
    your overall browsing experience!</p>
    
    <div class='botright'>
    <a href='http://www.crashie.com/' title='I do not wish to upgrade my Internet Explorer 6!'><img src='".UPGRADEELSEDIE_IMGLOC."yer-stupid.gif' alt='' border='0' onmouseover=\"this.src='".UPGRADEELSEDIE_IMGLOC."yer-stupid-hover.gif'\" onmouseout=\"this.src='".UPGRADEELSEDIE_IMGLOC."yer-stupid.gif'\" style='margin-right:40px;' /></a>
    <a href='http://www.microsoft.com/windows/downloads/ie/getitnow.mspx' title='Click here to upgrade to the latest version of Internet Explorer!'><img src='".UPGRADEELSEDIE_IMGLOC."upgrade.gif' alt='' border='0' onmouseover=\"this.src='".UPGRADEELSEDIE_IMGLOC."upgrade-hover.gif'\" onmouseout=\"this.src='".UPGRADEELSEDIE_IMGLOC."upgrade.gif'\"/></a>
    </div>
    </body>
    </html>
    <!-- End of Code Generated by Upgrade Else Die Plugin By www.gaut.am -->
    "
    );
}

if($browser == $ie6){ 
    add_action('bb_head', 'upgrade_else_die_kill_ie6', -1);
}
?>