<?php
/*
Plugin Name: After the Deadline
Plugin URI: http://www.gaut.am/bbpress/plugins/after-the-deadline/
Description: After the Deadline Plugin checks spelling, style, and grammar in your bbPress forum posts.
Version: 1.0
Author: Gautam
Author URI: http://gaut.am/

	Original After the Deadline - Spell Checker bbPress Plugin Copyright 2009 Gautam (email: admin@gaut.am) (website: http://gaut.am)

	This program is free software; you can redistribute it and/or modify
	it under the terms of the GNU General Public License as published by
	the Free Software Foundation; either version 2 of the License, or
	(at your option) any later version.
	
	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.
	
	You should have received a copy of the GNU General Public License
	along with this program; if not, write to the Free Software
	Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

*/

/*
 Main PHP File for
 After the Deadline - Spell Checker Plugin
 (for bbPress) by www.gaut.am
*/

// Create Text Domain For Translations - no translations for the time being, actually there is almost nothing that can be translated
//load_plugin_textdomain('after-the-deadline', '/my-plugins/after-the-deadline/languages/');

//defines
define('ATD_vNum', '1.0'); //version number of the plugin
define('ATD_PLUGPATH', bb_get_option('uri').trim(str_replace(array(trim(BBPATH,"/\\"),"\\"),array("","/"),dirname(__FILE__)),' /\\').'/'); //full url path to the plugin

//functions below

function atd_button(){ //inserts AtD spell check button when called
	echo '<span class="atd_container"><img src="'.ATD_PLUGPATH.'images/atdbuttontr.gif"><a href="#postform" onclick="check();" id="checkLink">Check Spelling</a></span>';
}

function atd_css_js(){ //enqueues & prints scripts and styles
	if(bb_is_topic()){ //only when it is a topic
		echo "\n\n".'<!-- Start Of Code Generated By After the Deadline Plugin By www.gaut.am -->'."\n";
		wp_register_script('after-the-deadline-js3', ATD_PLUGPATH."scripts/atd.js",  array('jquery'), ATD_vNum);
		wp_print_scripts('after-the-deadline-js3');
		wp_register_script('after-the-deadline-js', ATD_PLUGPATH."scripts/jquery.atd.js", array('jquery'), ATD_vNum);
		wp_print_scripts('after-the-deadline-js');
		wp_register_script('after-the-deadline-js2', ATD_PLUGPATH."scripts/csshttprequest.js", ATD_vNum);
		wp_print_scripts('after-the-deadline-js2');
		wp_register_style('after-the-deadline-css', ATD_PLUGPATH.'css/atd.css', false, ATD_vNum, 'all');
		wp_print_styles('after-the-deadline-css');
		echo '<!-- End Of Code Generated By After the Deadline Plugin By www.gaut.am -->'."\n\n";
	}
}

//actions/filters/hooks below

add_action('pre_post_form', 'atd_button', 9999999); //to insert AtD automatically below the post textbox, should be after anything
add_action('bb_head', 'atd_css_js', 2); //enqueues & prints scripts and styles, only when it is a topic
?>